baseurl:
url: 'http://example.com'
markdown: kramdown
title: Jekyll Maps
map-tileset: >-
  https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
map-credits: >-
  <a target="_blank" href="https://github.com/svmatthews/jekyll-maps">Jekyll
  Maps</a> | Tiles: Stamen & OSM